wild_village:
    resource: "@wildVillageBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_register:
    path:     /user/register
    defaults: { _controller: AppBundle:Registration:register }

user_login:
    path:     /user/login
    defaults: { _controller: AppBundle:Security:login }

user_login_check:
    path:    /user/login/check
    defaults: { _controller: AppBundle:Security:check }

user_espace:
    path:     /user/espace
    defaults: { _controller: AppBundle:Espace:espace }

user_flux:
    path:     /user/flux
    defaults: { _controller: AppBundle:Flux:flux }

user_search:
    path:    /user/search
    defaults: { _controller: AppBundle:Default:search }